from pathlib import Path
from pptx import Presentation
from pptx.util import Inches, Pt
from datetime import datetime


class PresentationGenerator:

    def __init__(self):

        self.output_folder = Path("output/presentations")
        self.output_folder.mkdir(parents=True, exist_ok=True)

    def add_title_slide(self, prs):

        slide_layout = prs.slide_layouts[0]

        slide = prs.slides.add_slide(slide_layout)

        title = slide.shapes.title
        title.text = "AI Project Health Reporting Agent"

        subtitle = slide.placeholders[1]

        subtitle.text = (
            "Monthly Executive Portfolio Report\n\n"
            f"Generated on: {datetime.now().strftime('%d %B %Y')}\n"
            "Prepared for: Project Leadership Team\n"
            "Generated by: AI Project Health Reporting Agent"
        )

        title.text_frame.paragraphs[0].font.size = Pt(30)

        subtitle.text_frame.paragraphs[0].font.size = Pt(18)

    def add_portfolio_summary(self, prs, projects):

        slide = prs.slides.add_slide(prs.slide_layouts[5])

        slide.shapes.title.text = "Portfolio Overview"

        rows = len(projects) + 1
        cols = 4

        table = slide.shapes.add_table(
            rows,
            cols,
            Inches(0.3),
            Inches(1.0),
            Inches(9.0),
            Inches(2.0)
        ).table

        table.columns[0].width = Inches(3.8)
        table.columns[1].width = Inches(1.3)
        table.columns[2].width = Inches(1.2)
        table.columns[3].width = Inches(2.7)

        table.cell(0,0).text = "Project"
        table.cell(0,1).text = "Health Score"
        table.cell(0,2).text = "RAG"
        table.cell(0,3).text = "Status"

        for c in range(cols):
            header = table.cell(0, c).text_frame.paragraphs[0]
            header.font.bold = True
            header.font.size = Pt(18)

        for i, project in enumerate(projects, start=1):

            table.cell(i,0).text = project["project"]
            table.cell(i,1).text = str(project["score"])
            table.cell(i,2).text = project["rag"]

            if project["rag"] == "Green":
                status = "Healthy"

            elif project["rag"] == "Amber":
                status = "Needs Attention"

            else:
                status = "Critical"

            table.cell(i,3).text = status

            for j in range(cols):
                cell = table.cell(i, j).text_frame.paragraphs[0]
                cell.font.size = Pt(16)

        total = len(projects)
        green = sum(1 for p in projects if p["rag"]=="Green")
        amber = sum(1 for p in projects if p["rag"]=="Amber")
        red = sum(1 for p in projects if p["rag"]=="Red")

        textbox = slide.shapes.add_textbox(
            Inches(0.4),
            Inches(3.5),
            Inches(8.5),
            Inches(2)
        )

        tf = textbox.text_frame

        p = tf.paragraphs[0]
        p.text = "Portfolio Summary"
        p.font.bold = True
        p.font.size = Pt(20)

        summary = [
            f"Projects Analysed : {total}",
            f"Green Projects : {green}",
            f"Amber Projects : {amber}",
            f"Red Projects : {red}"
        ]

        for item in summary:
            para = tf.add_paragraph()
            para.text = item
            para.font.size = Pt(18)

    def add_project_slide(self, prs, project):

        slide = prs.slides.add_slide(prs.slide_layouts[5])

        slide.shapes.title.text = project["project"]

        # -------------------------------
        # Project Health
        # -------------------------------

        textbox = slide.shapes.add_textbox(
            Inches(0.5),
            Inches(0.7),
            Inches(8.5),
            Inches(0.7)
        )

        tf = textbox.text_frame

        p = tf.paragraphs[0]

        p.text = (
            f"Health Score : {project['score']}/100     "
            f"RAG Status : {project['rag']}"
        )

        p.font.bold = True
        p.font.size = Pt(20)

        # -------------------------------
        # Executive Summary
        # -------------------------------

        textbox = slide.shapes.add_textbox(
            Inches(0.5),
            Inches(1.4),
            Inches(8.5),
            Inches(1.2)
        )

        tf = textbox.text_frame

        p = tf.paragraphs[0]
        p.text = "Executive Summary"
        p.font.bold = True
        p.font.size = Pt(18)

        body = tf.add_paragraph()
        body.text = project["analysis"]["executive_summary"]
        body.font.size = Pt(16)

        # -------------------------------
        # Top Risks
        # -------------------------------

        textbox = slide.shapes.add_textbox(
            Inches(0.5),
            Inches(2.8),
            Inches(8.5),
            Inches(1.6)
        )

        tf = textbox.text_frame

        p = tf.paragraphs[0]
        p.text = "Top Risks"
        p.font.bold = True
        p.font.size = Pt(18)

        for risk in project["analysis"]["key_risks"]:

            para = tf.add_paragraph()
            para.text = "• " + risk
            para.font.size = Pt(16)

        # -------------------------------
        # Recommendations
        # -------------------------------

        textbox = slide.shapes.add_textbox(
            Inches(0.5),
            Inches(4.6),
            Inches(8.5),
            Inches(1.8)
        )

        tf = textbox.text_frame

        p = tf.paragraphs[0]
        p.text = "Recommendations"
        p.font.bold = True
        p.font.size = Pt(18)

        for rec in project["analysis"]["recommendations"]:

            para = tf.add_paragraph()
            para.text = "✓ " + rec
            para.font.size = Pt(16)

    def add_portfolio_recommendations(self, prs, projects):

        slide = prs.slides.add_slide(prs.slide_layouts[5])

        slide.shapes.title.text = "Portfolio Trends & Executive Actions"

        textbox = slide.shapes.add_textbox(
            Inches(0.5),
            Inches(0.8),
            Inches(8.5),
            Inches(5.5)
        )

        tf = textbox.text_frame

        p = tf.paragraphs[0]
        p.text = "Observed Portfolio Trends"
        p.font.bold = True
        p.font.size = Pt(20)

        total_projects = len(projects)
        amber = sum(1 for p in projects if p["rag"] == "Amber")
        red = sum(1 for p in projects if p["rag"] == "Red")
        green = sum(1 for p in projects if p["rag"] == "Green")

        trends = [
            f"{amber} out of {total_projects} projects are currently in Amber status.",
            "A high number of project tasks remain in the Not Started state.",
            "Schedule variance is affecting delivery timelines across the portfolio.",
            "Critical and Red tasks require proactive monitoring."
        ]

        for item in trends:
            para = tf.add_paragraph()
            para.text = "• " + item
            para.font.size = Pt(16)

        p = tf.add_paragraph()
        p.text = "\nExecutive Actions"
        p.font.bold = True
        p.font.size = Pt(20)

        actions = [
            "Prioritize all Red and Critical tasks.",
            "Review project schedules during weekly governance meetings.",
            "Improve stakeholder communication for at-risk projects.",
            "Monitor portfolio health weekly using the AI Project Health Reporting Agent."
        ]

        for item in actions:
            para = tf.add_paragraph()
            para.text = "✓ " + item
            para.font.size = Pt(16)

    def generate(self, projects):

        prs = Presentation()

        self.add_title_slide(prs)

        self.add_portfolio_summary(prs, projects)

        for project in projects:

            self.add_project_slide(prs, project)

        self.add_portfolio_recommendations(prs, projects)

        output = (
            self.output_folder /
            "Monthly_Project_Report.pptx"
        )

        prs.save(output)

        return output
